testy/Models/Prawa/DodajPrawoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace testy.Models
{
    public class DodajPrawoModel
    {

        public int PDT_WybranyTest { get; set; }
        public int ileWypelniono { get; set; }
        public int idPrawa { get; set; }
        public List<SelectListItem> PDT_Testy { get; set; }

        [Required(ErrorMessage = "Musisz podać wartość")]
        [StringLength(10, ErrorMessage = "Zbyt długa nazwa")]
        public string PDT_nazwaGrupy { get; set; }

        [Required(ErrorMessage = "Błędna wartość")]
        public int PDT_limitWypelnien { get; set; }

        [Required(ErrorMessage = "Błędna wartość")]
        public int PDT_iloscPytan { get; set; }

        [Required(ErrorMessage = "Błędna wartość")]
        public DateTime PDT_czasRozpoczecia { get; set; }

        [Required(ErrorMessage = "Błędna wartość")]
        public DateTime PDT_czasZakonczenia { get; set; }

        [Required(ErrorMessage = "Musisz podać wartość")]
        [StringLength(10, ErrorMessage = "Zbyt długie hasło")]
        public string PDT_haslo { get; set; }

        [Required(ErrorMessage = "Błędna wartość")]
        public int PDT_czasNaWykonanieWMinutach { get; set; }

        public int PDT_test_ID_FK { get; set; } 
    }
}

testy/Controllers/Admin/PrawaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using testy.Models;
using testy.Helpers.Admin;

namespace testy.Controllers.Admin
{
    public class PrawaController : Controller
    {
        [HttpGet]
        public ActionResult DodajNowe()
        {
            if (Session["Id"] != null)
            {
                DodajPrawoModel dane = new DodajPrawoModel();
                using (var db = new projektEntities())
                {
                    PrawaConHelper.PobierzTestyZbazy(db, dane, int.Parse(Session["Id"].ToString()));
                }
                return View(dane);
            }
            return RedirectToAction("Logowanie", "Admin");
        }


        [HttpPost]
        public ActionResult DodajNowe(DodajPrawoModel daneZFormularza)
        {
            if (Session["Id"] != null)
            {
                if (ModelState.IsValid)
                {
                    using (var db = new projektEntities())
                    {
                        PrawaDoTestu doZapisu = new PrawaDoTestu();
                        PrawaConHelper.ZapiszPrawo(daneZFormularza, doZapisu, db);
                        return RedirectToAction("Zarzadzaj");
                    }
                }
                using (var db = new projektEntities())
                {
                    PrawaConHelper.PobierzTestyZbazy(db, daneZFormularza, int.Parse(Session["Id"].ToString()));
                }
                return View(daneZFormularza);
            }
            return RedirectToAction("Logowanie", "Admin");
        }

        [HttpGet]
        public ActionResult Edytuj(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Logowanie", "Admin");

            int idWlasciciela = int.Parse(Session["Id"].ToString());
            DodajPrawoModel prawoDlaFormularza = new DodajPrawoModel();

            using (var db = new projektEntities())
            {
               var znalezionePrawoDoTestu = (from i in db.PrawaDoTestu
                    join e in db.test on i.PDT_test_ID_FK equals e.TES_nrTestu
                    where i.PDT_id == id && e.TES_wlasciciel_ID_FK == idWlasciciela
                    select i).FirstOrDefault();
                if (znalezionePrawoDoTestu == null)
                    return RedirectToAction("Zarzadzaj");
                PrawaConHelper.WypelnijModelPrawaDoEdycji(db, prawoDlaFormularza, idWlasciciela, znalezionePrawoDoTestu);
            }
            return View(prawoDlaFormularza);
        }

        [HttpPost]
        public ActionResult Edytuj(DodajPrawoModel daneZFormularza)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Logowanie", "Admin");
            PrawaDoTestu daneDoUpdate = new PrawaDoTestu();
            if (ModelState.IsValid)
            {
                PrawaConHelper.UpdatePrawaPrzepiszDaneZForm(daneZFormularza, daneDoUpdate);
                using (var db = new projektEntities())
                {
                    db.PrawaDoTestu.AddOrUpdate(daneDoUpdate);
                    db.SaveChanges();
                    return RedirectToAction("Zarzadzaj");
                }
            }
            using (var db = new projektEntities())
            {
                PrawaConHelper.PobierzTestyZbazy(db, daneZFormularza, int.Parse(Session["Id"].ToString()));
            }
            return View(daneZFormularza);
        }

        [HttpGet]
        public ActionResult Usun(int id)
        {
            if (Session["Id"] == null)
                return RedirectToAction("Logowanie", "Admin");

            using (var db = new projektEntities())
            {
                int idWlasciciela = int.Parse(Session["Id"].ToString());
                var czyIstniejePrawo = (from i in db.PrawaDoTestu
                    join e in db.test on i.PDT_test_ID_FK equals e.TES_nrTestu
                    where i.PDT_id == id && e.TES_wlasciciel_ID_FK == idWlasciciela
                    select i).FirstOrDefault();
                if (czyIstniejePrawo == null)
                    return RedirectToAction("Zarzadzaj");
                db.PrawaDoTestu.Remove(czyIstniejePrawo);
                db.SaveChanges();
            }
            return RedirectToAction("Zarzadzaj");
        }

        [HttpGet]
        public ActionResult Zarzadzaj()
        {
            if (Session["Id"] == null)
                return RedirectToAction("Logowanie", "Admin");

            List<PrawaDoTestu> prawaZTabeli = new List<PrawaDoTestu>();
            using (var db = new projektEntities())
            {
                int idWlasciciela = int.Parse(Session["Id"].ToString());
                PrawaConHelper.PrawaNalezaceDoUzytkownika(db, idWlasciciela, prawaZTabeli);
            }
            return View(prawaZTabeli);
        }
        
        [HttpGet]
        public ActionResult ZarzadzajPrawami()
        {
            if (Session["Id"] == null)
                return RedirectToAction("Logowanie", "Admin");
            return View();
        }
	}
}

testy/Views/Prawa/DodajNowe.cshtml
@model testy.Models.DodajPrawoModel
@{
    ViewBag.Title = "Dodaj nowe prawo";
}

@Scripts.Render("~/Scripts/anytime.5.0.5.min.js")
@Scripts.Render("~/Scripts/DateTimePickerHelper.js")
@Styles.Render("~/Content/css/anytime.5.0.5.min.css")

<script>
    $(document).ready(function () {
        setDateTimePicker('#czasRozpoczeciaButton', '#PDT_czasRozpoczecia');
        setDateTimePicker('#czasZakonczeniaButton', '#PDT_czasZakonczenia');
    });
</script>

<style>
    .ui-state-highlight, .ui-widget-content .ui-state-highlight {
        background: #dddddd;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Zezwól na wykonanie testu</h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Admin") -
                @Html.ActionLink("Wyżej", "ZarzadzajPrawami", "Prawa")
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 formularzLogowaniaAdmina bodyWidoku">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                
                <div class="editor-label">
                    Podaj nazwę grupy
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_nazwaGrupy)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_nazwaGrupy)
                </div>
                
                <div class="editor-label">
                    Podaj hasło do testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_haslo)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_haslo)
                </div>

                <div class="editor-label">
                    Podaj ilość miejsc
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_limitWypelnien)
                   
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_limitWypelnien)
                </div>

                <div class="editor-label">
                    Podaj czas w minutach na wykonanie testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasNaWykonanieWMinutach)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasNaWykonanieWMinutach)
                </div>

                <div class="editor-label">
                    Podaj ilość pytań
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_iloscPytan)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_iloscPytan)
                </div>

                <div class="editor-label">
                    Data rozpoczęcia testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasRozpoczecia)
                    
                </div>
    
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasRozpoczecia)
                    <button id="czasRozpoczeciaButton">
                        <img src="~/Content/calendar.png" />
                    </button>
                </div>

                <div class="editor-label">
                    Data zakończenia testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasZakonczenia)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasZakonczenia)
                    <button id="czasZakonczeniaButton">
                        <img src="~/Content/calendar.png" />
                    </button>
                </div>
                
                <div class="editor-label">
                    Wybierz test
                </div>
                <div class="editor-label">
                    @Html.DropDownListFor(model => model.PDT_WybranyTest, Model.PDT_Testy)
                </div>

                <input type="submit" value="Dodaj" />
            }
        </div>
    </div>
</div>

testy/Views/Prawa/Edytuj.cshtml
@model testy.Models.DodajPrawoModel

@{
    ViewBag.Title = "Edytuj prawo";
}

@Scripts.Render("~/Scripts/anytime.5.0.5.min.js")
@Scripts.Render("~/Scripts/DateTimePickerHelper.js")
@Styles.Render("~/Content/css/anytime.5.0.5.min.css")

<script>
    $(document).ready(function() {
        setDateTimePicker('#czasRozpoczeciaButton', '#PDT_czasRozpoczecia');
        setDateTimePicker('#czasZakonczeniaButton', '#PDT_czasZakonczenia');
    });
</script>

<style>
    .ui-state-highlight, .ui-widget-content .ui-state-highlight {
        background: #dddddd;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Edytuj prawo</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 formularzLogowaniaAdmina bodyWidoku">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="editor-label">
                    Podaj nazwę grupy
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_nazwaGrupy)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_nazwaGrupy)
                </div>

                <div class="editor-label">
                    Podaj hasło do testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_haslo)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_haslo)
                </div>

                <div class="editor-label">
                    Podaj ilość miejsc
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_limitWypelnien)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_limitWypelnien)
                </div>

                <div class="editor-label">
                    Podaj czas w minutach na wykonanie testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasNaWykonanieWMinutach)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasNaWykonanieWMinutach)
                </div>

                <div class="editor-label">
                    Podaj ilość pytań
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_iloscPytan)
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_iloscPytan)
                </div>

                <div class="editor-label">
                    Data rozpoczęcia testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasRozpoczecia)
                </div>
                <div id="pickdate" class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasRozpoczecia)
                    <button id="czasRozpoczeciaButton">
                        <img src="~/Content/calendar.png" />
                    </button>
                </div>
                <div class="editor-label">
                    Data zakończenia testu
                </div>
                <div class="editor-label">
                    @Html.ValidationMessageFor(model => model.PDT_czasZakonczenia)
                    
                </div>
                <div class="editor-label">
                    @Html.EditorFor(model => model.PDT_czasZakonczenia)
                    <button id="czasZakonczeniaButton">
                        <img src="~/Content/calendar.png" />
                    </button>
                </div>

                <div class="editor-label">
                    Wybierz test
                </div>
                <div class="editor-label">
                    @Html.DropDownListFor(model => model.PDT_WybranyTest, Model.PDT_Testy)
                </div>
                
                <input type="hidden" name="idPrawa" value="@Model.idPrawa" />
                <input type="hidden" name="ileWypelniono" value="@Model.ileWypelniono" />
                <input type="hidden" name="PDT_test_ID_FK" value="@Model.PDT_test_ID_FK" />
                <input type="submit" value="Zapisz zmiany" />
            }
        </div>
    </div>
</div>

testy/Views/Prawa/Zarzadzaj.cshtml
@model IEnumerable<testy.Models.PrawaDoTestu>
    @{
        ViewBag.Title = "Zarządzaj";
    }


    <div class="container">
        <div class="row">
            <div class="col-xs-12 headerWidoku">
                <h2>Zarządzaj</h2>
                <h4>
                    @Html.ActionLink("Home", "Index", "Admin") -
                    @Html.ActionLink("Wyżej", "ZarzadzajPrawami", "Prawa")
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="CSSTableGenerator" style="margin: 0 auto;">
                    <tr>
                        <td></td>
                        <td>Grupa</td>
                        <td>Nazwa Testu</td>
                        <td>Limit</td>
                        <td>Czas (min)</td>
                        <td>Obowiązywanie</td>
                        <td>Edytuj</td>
                        <td>Usuń</td>
                    </tr>
                    @{ var i = 0; }
                    @foreach (var item in Model)
                    {
                        i++;
                        <tr>
                            <td>@i</td>
                            <td>@item.PDT_nazwaGrupy</td>
                            <td>@item.PDT_test_ID_FK</td>
                            <td>@item.PDT_ileWypelniono/@item.PDT_limitWypelnien</td>
                            <td>@item.PDT_czasNaRozwizanie</td>
                            <td>@item.PDT_czasRozpoczecia - @item.PDT_czasZakonczenia</td>
                            <td>@Html.ActionLink("Edytuj", "Edytuj", new { id = @item.PDT_id })</td>
                            <td>@Html.ActionLink("Usun", "Usun", new { id = @item.PDT_id })</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

testy/Views/Prawa/ZarzadzajPrawami.cshtml
@{
    ViewBag.Title = "Zarządzaj prawami";
}

<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Prawa dostępu</h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Admin") 
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div class="kwadrat dodajNowePrawoKwadrat">
                @Html.ActionLink("Dodaj nowe", "DodajNowe", "Prawa")
            </div>
        </div>
        <div class="col-xs-6">
            <div class="kwadrat zarzadzajPrawemKwadrat">
                @Html.ActionLink("Zarządzaj", "Zarzadzaj", "Prawa")
            </div>
        </div>
    </div>
    </div>