testy/Models/Wyniki.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyniki
    {
        public Wyniki()
        {
            this.UdzieloneOdpowiedzi = new HashSet<UdzieloneOdpowiedzi>();
        }
    
        public decimal WYN_ID { get; set; }
        public string WYN_imieStudenta { get; set; }
        public string WYN_nazwiskoStudenta { get; set; }
        public string WYN_grupaStudenta { get; set; }
        public decimal WYN_punkty { get; set; }
        public string WYN_ip { get; set; }
        public Nullable<decimal> WYN_test_ID_FK { get; set; }
    
        public virtual test test { get; set; }
        public virtual ICollection<UdzieloneOdpowiedzi> UdzieloneOdpowiedzi { get; set; }
    }
}

testy/Models/Wyniki/PokazWynikiModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace testy.Models
{
    public class PokazWynikiModel
    {
        [Required(ErrorMessage = "Musisz podać wartość")]
        [StringLength(20, ErrorMessage = "Zbyt długa nazwa")]
        public string NazwaGrupy { get; set; }
    }
}

testy/Controllers/Admin/WynikiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testy.Helpers.Admin;
using testy.Models;

namespace testy.Controllers.Admin
{
    public class WynikiController : Controller
    {
        [HttpGet]
        public ActionResult ZarzadzajWynikami()
        {
            if (CzyMaPrawaAdmina(Role.Admin))
                return RedirectToAction("Logowanie", "Admin");
            return View();
        }

        [HttpGet]
        public ActionResult WedlugGrupy()
        {
            if (CzyMaPrawaAdmina(Role.Admin))
                return RedirectToAction("Logowanie", "Admin");
            return View();
        }

        [HttpPost]
        public ActionResult WedlugGrupy(PokazWynikiModel daneZFormularza)
        {
            if (CzyMaPrawaAdmina(Role.Admin))
                return RedirectToAction("Logowanie", "Admin");
            return RedirectToAction("Wyniki/" + daneZFormularza.NazwaGrupy);
        }


        [HttpGet]
        public ActionResult Wyniki(string id = null)
        {
            if (CzyMaPrawaAdmina(Role.Admin))
                return RedirectToAction("Logowanie", "Admin");
            int idWlasciciela = int.Parse(Session["Id"].ToString());

            List<Wyniki> wszystkieWyniki;
            using (var db = new projektEntities())
            {
                if (id == null)
                {
                    wszystkieWyniki = (from i in db.Wyniki
                                       join d in db.test on i.WYN_test_ID_FK equals d.TES_nrTestu
                                       where d.TES_wlasciciel_ID_FK == idWlasciciela
                                       orderby i.WYN_ID descending
                                       select i).ToList();
                }else
                {
                    wszystkieWyniki = (from i in db.Wyniki
                                       join d in db.test on i.WYN_test_ID_FK equals d.TES_nrTestu
                                       where d.TES_wlasciciel_ID_FK == idWlasciciela
                                       && i.WYN_grupaStudenta == id
                                       orderby i.WYN_ID descending
                                       select i).ToList();
                }
            }
            if (wszystkieWyniki == null)
                wszystkieWyniki = new List<Wyniki>();
            return View(wszystkieWyniki);
        }

        private bool CzyMaPrawaAdmina(Role ob)
        {
            return Session["Rola"] != null && !Session["Rola"].ToString().Equals(ob.ToString());
        }
    }
}

testy/Views/Wyniki/WedlugGrupy.cshtml
@model testy.Models.PokazWynikiModel
@{
    ViewBag.Title = "Podaj grupę";
}


<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Podaj nazwę grupy</h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Admin") -
                @Html.ActionLink("Wyżej", "ZarzadzajWynikami", "Wyniki")
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div style="margin: 0 auto; width: 60%">
                <div style="text-align:center">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)

                        <div class="editor-label">
                            Nazwa grupy
                        </div>
                        <div class="editor-label">
                            @Html.ValidationMessageFor(model => model.NazwaGrupy)
                        </div>
                        <div class="editor-label">
                            @Html.EditorFor(model => model.NazwaGrupy)
                        </div>

                        <input type="submit" value="Pokaż testy" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

testy/Views/Wyniki/Wyniki.cshtml
@model IEnumerable<testy.Models.Wyniki>
@{
    ViewBag.Title = "Wszystkie";
}


<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Wyniki</h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Admin") -
                @Html.ActionLink("Wyżej", "ZarzadzajWynikami", "Wyniki")
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <table class="CSSTableGenerator" style="margin: 0 auto;">
                <tr>
                    <td></td>
                    <td>Imię</td>
                    <td>Nazwisko</td>
                    <td>Grupa</td>
                    <td>Punkty</td>
                    <td>Zobacz odpowiedzi</td>
                </tr>
                @{ var i = 0; }
                @foreach (var item in Model)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@item.WYN_imieStudenta</td>
                        <td>@item.WYN_nazwiskoStudenta</td>
                        <td>@item.WYN_grupaStudenta</td>
                        <td>@item.WYN_punkty</td>
                        <td>@Html.ActionLink("Odpowiedzi", "Odpowiedzi", new { id = @item.WYN_ID })</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

testy/Views/Wyniki/ZarzadzajWynikami.cshtml
@{
    ViewBag.Title = "Zarzadzaj wynikami";
}
<div class="container">
    <div class="row">
        <div class="col-xs-12 headerWidoku">
            <h2>Zarządzaj wynikami</h2>
            <h4>
                @Html.ActionLink("Home", "Index", "Admin")
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div class="kwadrat dodajNowyTestKwadrat">
                @Html.ActionLink("Wszystkie", "Wyniki", "Wyniki")
            </div>
        </div>
        <div class="col-xs-6">
            <div class="kwadrat zarzadzajTestamiKwadrat">
                @Html.ActionLink("Według grupy", "WedlugGrupy", "Wyniki")
            </div>
        </div>
    </div>
</div>